### ISSUE TITLE
Generate a dist files

### ISSUE THREAD

**Issue by fabiorogeriosj** [dotenorio/clipboard-manager-electron#1]
Using the electron-packager, create a dist files for download.

**Comment by dotenorio** [comment]
A manual option for now - https://github.com/dotenorio/clipboard-manager-electron/releases/latest

Now we need do this automatic 👍

**Comment by dotenorio** [comment]
The release was automated. Now i need to create a installer. :)

**Comment by dotenorio** [comment]
Installer Created! closing..
