### ISSUE TITLE
Many Linux distro have issues with tray elements 

### ISSUE THREAD

**Issue by savannahar68** [dotenorio/clipboard-manager-electron#19]
May new linux distro have issues with tray app context menu, and so they aren't displayed

Reproduce it in : 
Ubuntu 19.10
POP OS - 19.10

Quick fix : 
Install gnome-extension => google chrome extension
after that enable this extension
https://extensions.gnome.org/extension/615/appindicator-support/

We can update this in readme, if it is generic to other linux distro too

**Comment by dotenorio** [comment]
It don't work for me, sorry!

**Comment by savannahar68** [comment]
@dotenorio  Which Linux flavour and version did you tried it on?

**Comment by dotenorio** [comment]
Ubuntu 19.10
