### ISSUE TITLE
Please publish to npm

### ISSUE THREAD

**Issue by eptaccio** [dotenorio/clipboard-manager-electron#2]

**Comment by dotenorio** [comment]
Help me to do this?

**Comment by dotenorio** [comment]
Anyone?

**Comment by savannahar68** [comment]
Hi, @dotenorio I would like to work on this issue.
If no one is working on this, please assign this to me.

**Comment by dotenorio** [comment]
HIIIIII
THANK'S
This job it's only for you now :heart:

**Comment by savannahar68** [comment]
@dotenorio On it captain!

**Comment by savannahar68** [comment]
@dotenorio want more details, what do you mean by publishing to npm.

**Comment by dotenorio** [comment]
https://www.npmjs.com/package/clipboard-manager-electron
