### ISSUE TITLE
Feature Request - Clipboard History UI

### ISSUE THREAD

**Issue by savannahar68** [dotenorio/clipboard-manager-electron#20]
I really like the default window's history application, which has UI support too.
In windows 10, on click on WIN + C it show a small UI with all the clipboard history, where we can move up and down with arrows and select the clip which we want in our clipboard.

Linux and Mac lack this kind of application.

This is how window's clipboard history looks like - 

![image](https://user-images.githubusercontent.com/20986069/79135310-c4fdf700-7dcc-11ea-8d2f-a4a31af79384.png)

I would like to work on this feature, this is how I plan to proceed with - 

* On installation prompt a window with textbox asking the user for their keyboard shortcut preference
* In electron app, listen for that shortcut, on call launch small clipboard history UI with all the clips
* Provide mouse support or keyboard arrow support(up/down) to select history.
* On selecting history (Click on mouse/ enter via keyboard) close the clipboard history UI.
* Enhance tray menu to allow user to change shortcut, if he wants to.

@dotenorio if you approve this, please assign this to me.

**Comment by savannahar68** [comment]
@dotenorio do you want me to go with basic HTML, CSS, JS or React/Angular?

**Comment by dotenorio** [comment]
I prefer basic :)
