### ISSUE TITLE
Big icon on Mac

### ISSUE THREAD

**Issue by dotenorio** [dotenorio/clipboard-manager-electron#21]
![image](https://user-images.githubusercontent.com/3117833/80032712-f27c2c00-84c1-11ea-8bb2-1f762aebcbb0.png)

**Comment by dotenorio** [comment]
Thanks @brunoxd13!

**Comment by paddy-exe** [comment]
Hey there @dotenorio,
it seems like this is a general electron issue: https://github.com/electron/electron/issues/9642

Ironically though, it works for me on MacOS Catalina 10.15.5:
<img width="303" alt="grafik" src="https://user-images.githubusercontent.com/38077837/89549852-2842e780-d809-11ea-9d17-71bbb7245b9c.png">

Greetings,
Patrick

**Comment by dotenorio** [comment]
Ow.. Thanks @paddy-exe!
I'm happy it works in your Mac and for your feedback :smiley:
