### ISSUE TITLE
Blank entry added

### ISSUE THREAD

**Issue by savannahar68** [dotenorio/clipboard-manager-electron#25]
On copying without selecting anything adds a blank entry.

Steps to reproduce : 
1. Just click Ctrl+C when the app is running
2. Check the system tray

Output :
* Blank entry is added for that particular copy which does nothing

Expected Behavior :
* We should check the clipboard content and then if it is a blank entry, then ignore it

If you feel this needs to be resolved, let me know I would like to fix this!

**Comment by dotenorio** [comment]
i need to test it, but if you know how resolve it.. Let's go my friend!

**Comment by savannahar68** [comment]
@dotenorio sorry my bad, the blank entry appears when we copy a space. Though it is valid but doesn't look good. Can we do something about this?

Check the screenshot : 

![duplicateClips](https://user-images.githubusercontent.com/20986069/82344485-b92bd300-9a11-11ea-9aff-5fc2448aeb15.png)

**Comment by dotenorio** [comment]
Maybe show in list

X spaces

or

blank line

or

simple consider `space` on window to make lines with same height (i prefer this)
