### ISSUE TITLE
I need help to do this work fine in linux

### ISSUE THREAD

**Issue by dotenorio** [dotenorio/clipboard-manager-electron#3]
I try to run just an `npm start` and doesn't works. And when i generate a build with `npm run build-linux` it open but don't register the clipboard content.

**Comment by alotoftype** [comment]
I will look into this

**Comment by dotenorio** [comment]
Thanks, if you need i can to explain anything about the project.

**Comment by alotoftype** [comment]
@dotenorio sure I am open to hearing more about the project

**Comment by dotenorio** [comment]
* Really had a problem with copied.json :heavy_check_mark: 
* I discovered `tray.displayBallon() only works in Windows, i used another module to notificate on linux  :heavy_check_mark: 
* The module `electron-clipboard-extended` doesn't work fine in linux, i was reimplements this feature, but more simple :heavy_check_mark: 

And is it!!

Thanks for your help and get lastest release and test. 
Do this and the comunity will win :smile:
